### ISSUE TITLE
Set 'vmemsize' to 4MB

### ISSUE THREAD

**Issue by PoloniumRain** [MrDiagnose/Windows98-install-scripts-DosBox-X#2]
Hey, love this script, **very** useful!

But can you change the VRAM size for the S3 Trio64?

In the `win98_run.conf` file it has `vmemsize = 8` but the Windows drivers for the S3 Trio64 do not support more than 4MB, so it defaults to using just 2.5MB in Windows 98 (see image below). If you change this setting to `vmemsize = 4` it will then correctly recognise 4MB in Windows, and some games require 4MB to run.

![image](https://user-images.githubusercontent.com/50634894/180641113-65ba70a0-27df-49da-99d2-0c8e65ca4349.png)

**Comment by MrDiagnose** [comment]
done
